app/models.py
from flask_login import UserMixin
from app.database import db
from datetime import datetime

class Doctor(UserMixin, db.Model):
    __tablename__ = "doctor"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=False, nullable=False)
    surname = db.Column(db.String(80), unique=False, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(80), unique=False, nullable=False)

    patient = db.relationship('Patient', secondary='visit', back_populates='doctor')

    def __init__(self, name, surname, email, password):
        self.name = name
        self.surname = surname
        self.email = email
        self.password = password

    def to_json(self):
        return {"name": self.name,
                "email": self.email}

    def get_type(self):
        return self.__tablename__
    
    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)


class Patient(UserMixin, db.Model):
    __tablename__ = "patient"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=False, nullable=False)
    surname = db.Column(db.String(80), unique=False, nullable=False)
    password = db.Column(db.String(80), unique=False, nullable=False)
    sex = db.Column(db.Boolean, unique=False, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    pesel = db.Column(db.String(80), unique=True, nullable=False)
    phone = db.Column(db.String(80), unique=True, nullable=False)

    doctor = db.relationship('Doctor', secondary='visit', back_populates='patient')


    def __init__(self, name, surname, password, sex, pesel, phone, email):
        self.name = name
        self.surname = surname
        self.password = password
        self.sex = sex
        self.pesel = pesel
        self.phone = phone
        self.email = email

    def get_type(self):
        return self.__tablename__
    
    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)

class Visit(db.Model):
    __tablename__ = "visit"

    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, unique=False,
                     nullable=True, default=datetime.now().replace(second=0, microsecond=0))
    doctor_id = db.Column(db.Integer, db.ForeignKey('doctor.id'))
    patient_id = db.Column(db.Integer, db.ForeignKey('patient.id'))

    def __init__(self, date, doctor_id, patient_id):
        self.date = date
        self.doctor_id = doctor_id
        self.patient_id = patient_id

app/views.py
from flask import render_template, Blueprint, request, redirect, flash, session
from flask_login import login_user, logout_user, login_required

from app.database import db
from app.models import Doctor, Patient, Visit

views = Blueprint('views', __name__,
                  template_folder='templates', static_folder='static')


@views.route('/')
def home():
    return render_template('home.html')


@views.route('/registration', methods=['GET', 'POST'])
def registration():
    if request.method == 'POST':
        name = request.form['name']
        surname = request.form['surrname']
        pesel = request.form['pesel']
        sex = int(request.form['sex'])
        password = request.form['password']
        email = request.form['email']
        phone = request.form['phone']
        user = Patient.query.filter_by(pesel=pesel).first()

        if not user:
            flash('Rejestracja przebiegła pomyślnie')

            user = Patient(name=name,
                        surname=surname,
                        pesel=pesel,
                        sex=sex,
                        password=password,
                        phone=phone,
                        email=email)

            db.session.add(user)
            db.session.commit()
            db.session.close()

            return redirect('/')
        else:
            flash('Użytkownik już istnieje w bazie')
            return redirect('/registration')

    return render_template('registration.html')


@views.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user_type = request.form['choosePre']

        print(user_type)

        session['login_type'] = user_type

        if str(user_type) == "doctor":
            user = Doctor.query.filter_by(email=email).first()
        elif str(user_type) == "patient":
            user = Patient.query.filter_by(email=email).first()
            
        if not user or not user.password == password:
            flash('Sprawdź, czy wprowadzone dane są poprawne')
            return redirect('/login')

        login_user(user)
        flash('Zalogowano pomyślnie')
        return redirect('/')

    return render_template('login.html')


@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect('/')


@views.route('/test')
def test():
    Doctor.query.delete()
    db.session.commit()
    user = Doctor.query.all()
    return f'{[i.email for i in user]}'

@views.route('/visit-list/<id>', methods=['GET', 'POST'])
@login_required
def patientList(id):
    visit_list = db.engine.execute(f'SELECT DISTINCT visit.date, patient.name, patient.surname, patient.phone FROM visit, patient WHERE visit.doctor_id == {id}')
    print(visit_list)
    return render_template('patient-list.html', visit_list=visit_list)

@views.route('/patient-list/delete/<int:id>', methods=['POST'])
@login_required
def patientDelete(id):
    Patient.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect('/patient-list')

@views.route('/user-details/<id>', methods=['GET', 'POST'])
@login_required
def userDetails(id):
    users = Patient.query.filter_by(id=id)

    return render_template('user-details.html', users=users)

app/templates/home.html
{% extends "index.html" %}

{% block content %}
    <div>
        <section>
            <div class="categories">
                <header>
                    <h1>Nasza misja to:</h1>
                    <p>Kompleksowe świadczenie usług medycznych na najwyższym poziomie przez profesjonalną kadrę. </p>
                </header>
                <div class="author">
                    <figure>
                        <a href="#"><img src="../static/img/leki.jpg" alt="Alan Watts"></a>
                        <figcaption>Leki i recepty</figcaption>
                    </figure>
                </div>
                <div class="author">
                    <figure>
                        <a href="wpis.html"><img src="../static/img/szczep.jpg" alt="Anthony de Mello"></a>
                        <figcaption>Szczepionki COVID-19</figcaption>
                    </figure>
                </div>
                <div class="author">
                    <figure>
                        <a href="#"><img src="../static/img/przychodnia1.jpg" alt="Fryderyk Nietzsche"></a>
                        <figcaption>O nas</figcaption>
                    </figure>
                </div>
                <div class="author">
                    <figure>
                        <a href="#"><img src="../static/img/certy.jpg" alt="Platon"></a>
                        <figcaption> Nasze certyfikaty</figcaption>
                    </figure>
                </div>
                <div class="author">
                    <figure>
                        <a href="#"><img src="../static/img/kontakt.jpg" alt="Immanuel Kant"></a>
                        <figcaption>Kontakt</figcaption>
                    </figure>
                </div>
                <div class="author">
                    <figure>
                        <a href="#"><img src="../static/img/inter.jpg" alt="Ralph Waldo Emerson"></a>
                        <figcaption>e-Przychodnia</figcaption>
                    </figure>
                </div>
            </div>
        </section>

        <section id="newest">
            <div class="entries">
                <header>
                    <h1>Dlaczego warto skorzystać z naszych usług?</h1>
                </header>
                <div class="entry">
                    <div class="entryimg">
                        <img src="../static/img/przychodnia.jpg" alt="Anthony de Mello">
                    </div>
                    <div class="entrytxt">
                        <h2>Innowacyjna obsługa pacjenta</h2>
                        <p>Oferujemy swoim pacjentom wysoką jakość
                            oraz innowacyjność rozwiązań</p>
                    </div>
                </div>
                <div class="entry">
                    <div class="entryimg">
                        <img src="../static/img/inter.jpg" alt="Anthony de Mello">
                    </div>
                    <div class="entrytxt">
                        <h2>Blisko Ciebie</h2>
                        <p>Przychodnia w Kielcach</p>
                    </div>
                </div>
                <div class="entry">
                    <div class="entryimg">
                        <img src="../static/img/konon.jpg" alt="Anthony de Mello">
                    </div>
                    <div class="entrytxt">
                        <h2>Doświadczeni specjaliści</h2>
                        <p>Dysponujemy nowoczesnym sprzętem oraz doświadczony zespołem specjalistów </p>
                    </div>
                </div>
            </div>
        </section>

        <section>
            <div class="contact">
                <header>
                    <h1>Kontakt z przychodnią</h1>
                    <p>Jeśli masz jakieś pytania lub zastrzeżenia to zapraszam do kontaktu telefonicznego: 777 888
                        999</p>
                </header>
                <a href="#" class="bluebutton">Kontakt</a>
            </div>
        </section>
    </div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="pl">
<head>

    <meta charset="utf-8">
    <title>Przychodnia piguła</title>

    <meta http-equiv="X-Ua-Compatible" content="IE=edge,chrome=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fontello.css') }}">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;subset=latin-ext" rel="stylesheet">

</head>

<body>
<h1 class="logo">Przychodnia piguła </h1>
<nav id="topnav">
    <ul class="menu">
        <li><a href="{{ url_for('views.home') }}">Strona główna</a></li>
        <li><a href="#">O nas</a></li>
        <li><a href="#">Kontakt</a></li>
        {% if not current_user.is_authenticated %}
            <li><a href="{{ url_for('views.login') }}">Zaloguj się</a></li>
            <li><a href="{{ url_for('views.registration') }}">Zarejestruj się</a></li>
        {% endif %}
        {% if current_user.is_authenticated %}
            {% if current_user.get_type() == "doctor" %}
                <li><a href="{{ url_for('views.patientList', id=current_user.get_id()) }}">Wizyty</a></li>
            {% endif %}
            {% if current_user.get_type() == "patient" %}
                <li><a href="{{ url_for('views.userDetails', id=current_user.get_id()) }}">Karta pacjenta</a></li>
            {% endif %}
            <li><a href="{{ url_for('views.logout') }}">Wyloguj się</a></li>
            <li style="text-align: right">Zalogowany jako, {{ current_user.name }} {{ current_user.surname }}</li>
        {% endif %}
    </ul>
</nav>
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <div class="my_gap"></div>
        <div style="background-color: #ff514c" class="container">
            <h3 style="text-align: center">{{ messages[0] }}</h3>
        </div>
    {% endif %}
{% endwith %}

<div id="content">
    {% block content %}
    {% endblock %}
</div>

<div class="info">
    Wszelkie prawa zastrzeżone &copy; 2022 Dziękuję za wizytę!
</div>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script>

</html>

app/templates/login.html
{% extends "index.html" %}

{% block content %}
<div class="container my_gap">
    <h2 style="text-align: center">Logowanie</h2>
</div>
<div class="container">
    <form action="" method="post">
        <div class="form-group my_gap">
            <label for="email">Adres email</label>
            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp"
                   placeholder="Adres email" required>
        </div>
        <div class="form-group my_gap">
            <label for="password">Hasło</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Hasło" required>
        </div>
        <select class="form-select my_gap" aria-label="Default select example" name="choosePre" id="choosePre">
  <option selected>Wybierz kim jesteś</option>
  <option value="doctor">Lekarz</option>
  <option value="patient">Pacjent</option>
</select>
        <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
    </form>
</div>
{% endblock %}

app/templates/patient-card.html
{% extends "index.html" %}

{% block content %}
<div class="container my_gap">
    <h2 style="text-align: center">Karta pacjenta</h2>
</div>
<div class="container">
    
</div>
{% endblock %}

app/templates/patient-list.html
{% extends "index.html" %}

{% block content %}
    <div class="container my_gap">
        <h2 style="text-align: center">Umówione wizyty</h2>
    </div>
    <div class="container">
        <div class="row">
            {% for visit in visit_list %}
                <div class="col-sm-6 my_gap">
                    	<div class="card" style="width: 18rem;">
                      	<div class="card-body">
                            <h5 class="card-title" style="color: black">{{visit[1]}} {{visit[2]}}</h5>
                            <p class="card-text" style="color: black">
                                Wizyta: {{ visit.date }}</p>
                            <p class="card-text" style="color: black">
                                Numer telefonu: {{ visit[3] }}</p>
                      	</div>
                    	</div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/registration.html
{% extends "index.html" %}

{% block content %}
    <div class="container my_gap">
        <h2 style="text-align: center">Rejestracja</h2>
    </div>
    <div class="container">
        <form action="" method="post">
            <div class="row">
                <div class="col">
                    <label for="name">Imię</label>
                    <input type="text" class="form-control" name="name" placeholder="Imię" required>
                </div>
                <div class="col">
                    <label for="surrname">Nazwisko</label>
                    <input type="text" class="form-control" name="surrname" placeholder="Nazwisko" required>
                </div>
            </div>
            <div class="form-group my_gap">
                <label for="email">Adres email</label>
                <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp"
                       placeholder="Adres email" required>
            </div>
            <div class="form-group my_gap">
                <label for="phone">Numer telefonu</label>
                <input type="text" class="form-control" name="phone" placeholder="Numer telefonu" required>
            </div>
            <div class="form-group my_gap">
                <label for="pesel">PESEL</label>
                <input type="text" class="form-control" name="pesel" placeholder="PESEL" required>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="sex" id="sex_men" value='0'>
                <label class="form-check-label" for="sex_men">
                Mężczyzna
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="sex" id="sex_women" value='1' checked>
                <label class="form-check-label" for="sex_women">
                    Kobieta
                </label>
            </div>
            <div class="form-group my_gap">
                <label for="password">Hasło</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Hasło" required>
            </div>
            <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit
            </button>
        </form>
    </div>
{% endblock %}

app/templates/user-details.html
{% extends "index.html" %}

{% block content %}
<div class="container my_gap">
    <h2 style="text-align: center">Karta pacjenta</h2>
</div>
<div class="container my_gap">
    {% for user in users %}
    <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
      <li class="list-group-item">{{ user.name }} {{ user.surname }}</li>
      {% if user.sex == "0" %}
        <li class="list-group-item">Płeć: Mężczyzna</li>
      {% else %}
        <li class="list-group-item">Płeć: Kobieta</li>
      {% endif %}
    <li class="list-group-item">PESEL: {{ user.pesel }}</li>
    <li class="list-group-item">Numer telefonu: {{ user.phone }}</li>
  </ul>
    </div>
    {% endfor %}
</div>
{% endblock %}